# Permalinks
permalink:           pretty

# Setup
title:               Yang Xinlin
tagline:             Product Design from China beijing.
url:                 http://yangxinlin.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Yang Xinlin
  url:               https://twitter.com/xinlinyang
  email:             yangxinlins@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/jamigibbs/portfolio
google_analytics:    UA-3363703-15
twitter:             xinlinyang
github:              yangxinlin
dribbble:            yangxinlin

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
